# Generated by Django 3.0.3 on 2020-02-14 07:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_auto_20200214_1545'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeagueTracker',
            new_name='League',
        ),
    ]
